version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: contact_service_db_container
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - my_db_data:/var/lib/postgresql/data

  app:
    image: contact-management-service:latest
    container_name: contact_service_app_container
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgre
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  my_db_data:
