version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: contact_service_container
    environment:
      POSTGRES_DB: senoussial
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - my_db_data:/var/lib/postgresql/data

volumes:
  my_db_data:
