version: '3.8'
networks:
    main-network:
        external: false
        name: ${NETWORK_NAME}
services:
  postgres:
    image: postgres:latest
    container_name: contact_service_db_container
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - my_db_data:/var/lib/postgresql/data
    networks:
        - main-network
  app:
    image: contact-management-service:latest
    container_name: contact_service_app_container
    hostname: ${CONTAINER_HOST}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CONTAINER_PORT=${CONTAINER_PORT}
    env_file:
      - ${ENV_FILE}
    ports:
      - ${APP_PORT}:${CONTAINER_PORT}
    depends_on:
      - postgres
    networks:
        - main-network

volumes:
  my_db_data: