server:
  port: ${CONTAINER_PORT:8080}
  address: ${CONTAINER_HOST:localhost}

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:contact_service_db}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        default_schema: ${SPRING_JPA_HIBERNATE_DEFAULT_SCHEMA:public}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}