# Server
SPRING_PROFILES_ACTIVE: qa
CONTAINER_PORT: ${CONTAINER_PORT:8080}
CONTAINER_HOST: ${CONTAINER_HOST}

# Database connection
POSTGRES_HOST: ${POSTGRES_HOST:localhost}
POSTGRES_PORT: ${POSTGRES_PORT:5432}
POSTGRES_DB: ${POSTGRES_DB:contact_service_db}
POSTGRES_USERNAME: ${POSTGRES_USERNAME}
POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
SPRING_JPA_HIBERNATE_DEFAULT_SCHEMA: ${POSTGRES_DEFAULT_SCHEMA:public}

management:
  endpoints:
    web:
      exposure:
        include: '*'

