name: Java CI/CD with Maven

on:
  push:
    branches: [ Contact-workflow ]
  pull_request:
    branches: [ Contact-workflow ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Build with Maven (Tests Skipped)
      run: mvn -B verify --file pom.xml -DskipTests
      # The verify phase includes compiling and packaging, but we're skipping tests with -DskipTests
